addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.2.1")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"          % "4.0.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.6")
addSbtPlugin("no.arktekk.sbt"   % "aether-deploy"       % "0.24.0")
